import { z } from "zod"
import type { Database } from "./supabase" // Import from generated types

// Re-export main types for convenience
export type Party = Database["public"]["Tables"]["parties"]["Row"]
export type Promoter = Database["public"]["Tables"]["promoters"]["Row"]
export type Contract = Database["public"]["Tables"]["contracts"]["Row"] & {
  party_a_name?: string
  party_b_name?: string
  promoter_name?: string
}

// Example Zod schema for a form (can be moved to a lib/validations folder)
export const promoterFormSchema = z.object({
  name_en: z.string().min(2, "English name is required."),
  name_ar: z.string().min(2, "Arabic name is required."),
  id_card_number: z.string().min(5, "ID card number is required."),
  // Add other promoter fields as necessary, e.g., status, employer_id, etc.
  // For example:
  // status: z.enum(["active", "inactive", "pending_review"]),
  // employer_id: z.string().uuid().nullable(),
  id_card_url: z.string().url().optional().nullable(),
  passport_url: z.string().url().optional().nullable(),
  // ... any other fields from your PromoterFormData
})

export type PromoterFormData = z.infer<typeof promoterFormSchema>

export const promoterStatusesList = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  { value: "pending_review", label: "Pending Review" },
  // Add other statuses if needed
]

// Extended types for Supabase joins
export type ContractRecord = Database["public"]["Tables"]["contracts"]["Row"] & {
  parties_contracts_employer_id_fkey?: { name_en: string | null; name_ar: string | null } | null
  parties_contracts_client_id_fkey?: { name_en: string | null; name_ar: string | null } | null
  promoters?: { name_en: string | null; name_ar: string | null } | null
}

export type BilingualPdfData = {
  first_party_name_en?: string | null
  first_party_name_ar?: string | null
  second_party_name_en?: string | null
  second_party_name_ar?: string | null
  promoter_name_en?: string | null
  promoter_name_ar?: string | null
  contract_start_date?: string | null
  contract_end_date?: string | null
  job_title?: string | null
  email?: string | null
}

// This file can be used for custom types not generated by Supabase.
// For example:
export type MyCustomType = {
  id: string
  name: string
}
