// This file will be generated by the Supabase CLI.
// Run: npx supabase gen types typescript --project-id <YOUR_PROJECT_REF> --schema public > types/supabase.ts
// Or for local dev: npx supabase gen types typescript --local > types/supabase.ts

// Example of what it might contain (will be much more extensive):
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      contracts: {
        Row: {
          id: string
          created_at: string
          updated_at?: string | null
          contract_number?: string | null
          is_current?: boolean | null
          pdf_url?: string | null
          user_id?: string | null
          first_party_id: string
          second_party_id: string
          promoter_id: string
          contract_valid_from?: string | null
          contract_valid_until?: string | null
          contract_start_date?: string | null
          contract_end_date?: string | null
          contract_value?: number | null
          job_title?: string | null
          status?: string | null
          work_location?: string | null
          email?: string | null
          contract_name?: string | null
          party_a?: string | null
          party_b?: string | null
          contract_type?: string | null
          terms?: string | null
          department?: string | null
          currency?: string | null
          end_date?: string | null
          duration?: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string | null
          contract_number?: string | null
          is_current?: boolean | null
          pdf_url?: string | null
          user_id?: string
          first_party_id: string
          second_party_id: string
          promoter_id: string
          contract_valid_from?: string | null
          contract_valid_until?: string | null
<<<<<<< HEAD
          job_title?: string | null
          status?: string | null
          work_location?: string | null
=======
>>>>>>> 2ca6fc48d74debda61bb0a128c96bc1d81dbb86a
          contract_start_date?: string | null
          contract_end_date?: string | null
          contract_value?: number | null
          job_title?: string | null
          status?: string | null
          work_location?: string | null
          email?: string | null
          contract_name?: string | null
          party_a?: string | null
          party_b?: string | null
          contract_type?: string | null
          terms?: string | null
          department?: string | null
          currency?: string | null
          end_date?: string | null
          duration?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string | null
          contract_number?: string | null
          is_current?: boolean | null
          pdf_url?: string | null
          user_id?: string
          first_party_id?: string
          second_party_id?: string
          promoter_id?: string
          contract_valid_from?: string | null
          contract_valid_until?: string | null
<<<<<<< HEAD
          job_title?: string | null
          status?: string | null
          work_location?: string | null
=======
>>>>>>> 2ca6fc48d74debda61bb0a128c96bc1d81dbb86a
          contract_start_date?: string | null
          contract_end_date?: string | null
          contract_value?: number | null
          job_title?: string | null
          status?: string | null
          work_location?: string | null
          email?: string | null
          contract_name?: string | null
          party_a?: string | null
          party_b?: string | null
          contract_type?: string | null
          terms?: string | null
          department?: string | null
          currency?: string | null
          end_date?: string | null
          duration?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contracts_first_party_id_fkey"
            columns: ["first_party_id"]
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_promoter_id_fkey"
            columns: ["promoter_id"]
            referencedRelation: "promoters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_second_party_id_fkey"
            columns: ["second_party_id"]
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      parties: {
        Row: {
          id: string
          name_en: string
          name_ar: string
          crn: string
          type?: "Employer" | "Client" | "Generic" | null
          role?: string | null
          cr_expiry_date?: string | null
          contact_person?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          address_en?: string | null
          address_ar?: string | null
          tax_number?: string | null
          license_number?: string | null
          license_expiry_date?: string | null
          status?: string | null
          notes?: string | null
          created_at?: string | null
          owner_id?: string | null
        }
        Insert: {
          id?: string
          name_en: string
          name_ar: string
          crn: string
          type?: "Employer" | "Client" | "Generic" | null
          role?: string | null
          cr_expiry_date?: string | null
          contact_person?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          address_en?: string | null
          address_ar?: string | null
          tax_number?: string | null
          license_number?: string | null
          license_expiry_date?: string | null
          status?: string | null
          notes?: string | null
          created_at?: string | null
          owner_id?: string | null
        }
        Update: {
          id?: string
          name_en?: string
          name_ar?: string
          crn?: string
          type?: "Employer" | "Client" | "Generic" | null
          role?: string | null
          cr_expiry_date?: string | null
          contact_person?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          address_en?: string | null
          address_ar?: string | null
          tax_number?: string | null
          license_number?: string | null
          license_expiry_date?: string | null
          status?: string | null
          notes?: string | null
          created_at?: string | null
          owner_id?: string | null
        }
        Relationships: []
      }
      promoters: {
        Row: {
          id: string
          name_en: string
          name_ar: string
          id_card_number: string
          id_card_url?: string | null
          passport_url?: string | null
          status?: string | null
          id_card_expiry_date?: string | null
          passport_expiry_date?: string | null
          notify_days_before_id_expiry?: number | null
          notify_days_before_passport_expiry?: number | null
          notes?: string | null
          created_at?: string | null
<<<<<<< HEAD
          // ... other fields
=======
          employer_id?: string | null
          outsourced_to_id?: string | null
          job_title?: string | null
          work_location?: string | null
          contract_valid_until?: string | null
>>>>>>> 2ca6fc48d74debda61bb0a128c96bc1d81dbb86a
        }
        Insert: {
          id?: string
          name_en: string
          name_ar: string
          id_card_number: string
          id_card_url?: string | null
          passport_url?: string | null
          status?: string | null
          id_card_expiry_date?: string | null
          passport_expiry_date?: string | null
          notify_days_before_id_expiry?: number | null
          notify_days_before_passport_expiry?: number | null
          notes?: string | null
          created_at?: string | null
<<<<<<< HEAD
          // ... other fields
=======
          employer_id?: string | null
          outsourced_to_id?: string | null
          job_title?: string | null
          work_location?: string | null
          contract_valid_until?: string | null
>>>>>>> 2ca6fc48d74debda61bb0a128c96bc1d81dbb86a
        }
        Update: {
          id?: string
          name_en?: string
          name_ar?: string
          id_card_number?: string
          id_card_url?: string | null
          passport_url?: string | null
          status?: string | null
          id_card_expiry_date?: string | null
          passport_expiry_date?: string | null
          notify_days_before_id_expiry?: number | null
          notify_days_before_passport_expiry?: number | null
          notes?: string | null
          created_at?: string | null
<<<<<<< HEAD
          // ... other fields
=======
          employer_id?: string | null
          outsourced_to_id?: string | null
          job_title?: string | null
          work_location?: string | null
          contract_valid_until?: string | null
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          id: string
          action: string
          entity_type: string
          entity_id: string
          details?: Json | null
          user_id?: string | null
          created_at: string
          table_name?: string | null
          record_id?: string | null
        }
        Insert: {
          id?: string
          action: string
          entity_type: string
          entity_id: string
          details?: Json | null
          user_id?: string | null
          created_at?: string
          table_name?: string | null
          record_id?: string | null
        }
        Update: {
          id?: string
          action?: string
          entity_type?: string
          entity_id?: string
          details?: Json | null
          user_id?: string | null
          created_at?: string
          table_name?: string | null
          record_id?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          type: string
          message: string
          created_at: string
          is_read: boolean
          user_email?: string | null
          related_contract_id?: string | null
          user_id?: string | null
          read?: boolean | null
        }
        Insert: {
          id?: string
          type: string
          message: string
          created_at?: string
          is_read?: boolean
          user_email?: string | null
          related_contract_id?: string | null
          user_id?: string | null
          read?: boolean | null
        }
        Update: {
          id?: string
          type?: string
          message?: string
          created_at?: string
          is_read?: boolean
          user_email?: string | null
          related_contract_id?: string | null
          user_id?: string | null
          read?: boolean | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          full_name?: string | null
          role?: string | null
          created_at?: string | null
        }
        Insert: {
          id?: string
          full_name?: string | null
          role?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          full_name?: string | null
          role?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      users: {
        Row: {
          id: string
          email: string
          role: string
          created_at: string
          profile_data?: Json | null
        }
        Insert: {
          id?: string
          email: string
          role: string
          created_at?: string
          profile_data?: Json | null
        }
        Update: {
          id?: string
          email?: string
          role?: string
          created_at?: string
          profile_data?: Json | null
        }
        Relationships: []
      }
      app_users: {
        Row: {
          id: string
          email: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          role?: string
          created_at?: string
        }
        Relationships: []
      }
      party_files: {
        Row: {
          id: string
          party_id: string
          file_name: string
          file_url: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          party_id: string
          file_name: string
          file_url: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          party_id?: string
          file_name?: string
          file_url?: string
          user_id?: string
          created_at?: string
        }
        Relationships: []
      }
      party_notes: {
        Row: {
          id: string
          party_id: string
          user_id: string
          note: string
          created_at: string
        }
        Insert: {
          id?: string
          party_id: string
          user_id: string
          note: string
          created_at?: string
        }
        Update: {
          id?: string
          party_id?: string
          user_id?: string
          note?: string
          created_at?: string
        }
        Relationships: []
      }
      party_tags: {
        Row: {
          id: string
          party_id: string
          tag: string
          created_at: string
        }
        Insert: {
          id?: string
          party_id: string
          tag: string
          created_at?: string
        }
        Update: {
          id?: string
          party_id?: string
          tag?: string
          created_at?: string
        }
        Relationships: []
      }
      party_activities: {
        Row: {
          id: string
          party_id: string
          activity_type: string
          details: string
          created_at: string
          user_id?: string | null
        }
        Insert: {
          id?: string
          party_id: string
          activity_type: string
          details: string
          created_at?: string
          user_id?: string | null
        }
        Update: {
          id?: string
          party_id?: string
          activity_type?: string
          details?: string
          created_at?: string
          user_id?: string | null
>>>>>>> 2ca6fc48d74debda61bb0a128c96bc1d81dbb86a
        }
        Relationships: []
      }
      // ... other tables
    }
    Views: {
      // ... views
    }
    Functions: {
      get_dashboard_analytics: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      files_per_month: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      // ... other functions
    }
    Enums: {
      // ... enums
    }
    CompositeTypes: {
      // ... composite types
    }
  }
}

// Helper types (optional, but can be useful)
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"]
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T]
// ... more helpers if needed
