import {
  type LucideIcon,
  Check,
  ChevronsUpDown,
  PlusCircle,
  Loader2,
  CalendarIcon,
  User,
  Mail,
  Phone,
  Building,
  Globe,
  ImageIcon,
  FileText,
  DollarSign,
  ClipboardList,
  Trash2,
  Edit,
  Eye,
  Download,
  Upload,
  X,
  AlertTriangle,
  Info,
  Bell,
  Settings,
  LayoutDashboard,
  Users,
  BarChart,
  ListChecks,
  History,
  Search,
  Filter,
  ArrowUpDown,
  MoreHorizontal,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Menu,
  LogOut,
  LogIn,
  Home,
  FileSignature,
  Briefcase,
  UserRound,
  Building2,
  CalendarDays,
  Euro,
  FileWarning,
  FileCheck,
  FileClock,
  FileX,
  FileQuestion,
  FileSliders,
  FileSearch,
  FileBadge,
  FileBarChart,
  FileSpreadsheet,
  FileTextIcon,
  FileJson,
  FileCode,
  FileTerminal,
  FileType,
  FileAudio,
  FileVideo,
  FileImage,
  FileIcon as FilePdf,
  FileIcon as FileWord,
  FileSpreadsheetIcon as FileExcel,
  FileIcon as FilePowerpoint,
  FileSpreadsheetIcon as FileCsv,
  FileArchiveIcon as FileZip,
  FileKey,
  FileLock,
  FileLockIcon as FileUnlock,
  ShieldIcon as FileShield,
  FileHeart,
  StarIcon as FileStar,
  FilePlus,
  FileMinus,
  FileEdit,
  FileIcon as FileEye,
  DownloadIcon as FileDownload,
  UploadIcon as FileUpload,
  Command,
  CreditCard,
  FileIcon,
  HelpCircle,
  Laptop,
  MoreVertical,
  Pizza,
  Plus,
  SunMedium,
  Twitter,
  ArrowRight,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  check: Check,
  chevronsUpDown: ChevronsUpDown,
  plusCircle: PlusCircle,
  loader: Loader2,
  calendar: CalendarIcon,
  user: User,
  mail: Mail,
  phone: Phone,
  building: Building,
  globe: Globe,
  image: ImageIcon,
  fileText: FileText,
  dollarSign: DollarSign,
  clipboardList: ClipboardList,
  trash: Trash2,
  edit: Edit,
  eye: Eye,
  download: Download,
  upload: Upload,
  x: X,
  alertTriangle: AlertTriangle,
  info: Info,
  bell: Bell,
  settings: Settings,
  dashboard: LayoutDashboard,
  users: Users,
  barChart: BarChart,
  listChecks: ListChecks,
  history: History,
  search: Search,
  filter: Filter,
  arrowUpDown: ArrowUpDown,
  moreHorizontal: MoreHorizontal,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  menu: Menu,
  logOut: LogOut,
  logIn: LogIn,
  home: Home,
  fileSignature: FileSignature,
  briefcase: Briefcase,
  userRound: UserRound,
  building2: Building2,
  calendarDays: CalendarDays,
  euro: Euro,
  fileWarning: FileWarning,
  fileCheck: FileCheck,
  fileClock: FileClock,
  fileX: FileX,
  fileQuestion: FileQuestion,
  fileSliders: FileSliders,
  fileSearch: FileSearch,
  fileBadge: FileBadge,
  fileBarChart: FileBarChart,
  filePie: FileSpreadsheet,
  fileSpreadsheet: FileExcel,
  fileTextIcon: FileTextIcon,
  fileJson: FileJson,
  fileCode: FileCode,
  fileTerminal: FileTerminal,
  fileType: FileType,
  fileArchive: FileZip,
  fileAudio: FileAudio,
  fileVideo: FileVideo,
  fileImage: FileImage,
  filePdf: FilePdf,
  fileWord: FileWord,
  filePowerpoint: FilePowerpoint,
  fileCsv: FileCsv,
  fileZip: FileZip,
  fileKey: FileKey,
  fileLock: FileLock,
  fileUnlock: FileUnlock,
  fileShield: FileShield,
  fileHeart: FileHeart,
  fileStar: FileStar,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  fileEdit: FileEdit,
  fileEye: FileEye,
  fileDownload: FileDownload,
  fileUpload: FileUpload,
  logo: Command,
  close: X,
  spinner: Loader2,
  post: FileText,
  page: FileIcon,
  media: ImageIcon,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Loader2,
  laptop: Laptop,
  twitter: Twitter,
}
